openapi: 3.0.0
info:
  title: Google Sheets API Proxy
  description: Прокси-сервис для работы с Google Sheets API через сервисный аккаунт
  version: 1.0.0
servers:
  - url: https://google-sheets-proxy-xxxxx.zeabur.app
    description: URL вашего микросервиса (замените на реальный после деплоя)
paths:
  /:
    get:
      operationId: getStatus
      summary: Проверка статуса сервиса
      responses:
        '200':
          description: Сервис работает
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Google Sheets API Proxy is running"
  /spreadsheets:
    get:
      operationId: listSpreadsheets
      summary: Получить список доступных таблиц Google Sheets
      responses:
        '200':
          description: Список таблиц
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1M50MTl_pWsov4yavKR_QdfHEOZqMpr63vbK46HHPAlA"
                    name:
                      type: string
                      example: "Моя таблица"
  /spreadsheets/{spreadsheetId}:
    get:
      operationId: getSpreadsheet
      summary: Получить информацию о таблице
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
          description: ID Google таблицы
          example: "1M50MTl_pWsov4yavKR_QdfHEOZqMpr63vbK46HHPAlA"
      responses:
        '200':
          description: Информация о таблице
          content:
            application/json:
              schema:
                type: object
  /spreadsheets/{spreadsheetId}/values/{range}:
    get:
      operationId: getValues
      summary: Получить значения из диапазона таблицы
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
          description: ID Google таблицы
          example: "1M50MTl_pWsov4yavKR_QdfHEOZqMpr63vbK46HHPAlA"
        - name: range
          in: path
          required: true
          schema:
            type: string
          description: Диапазон ячеек (например, 'Sheet1!A1:B10')
          example: "Sheet1!A1:B10"
      responses:
        '200':
          description: Значения из диапазона
          content:
            application/json:
              schema:
                type: object
                properties:
                  range:
                    type: string
                    example: "Sheet1!A1:B10"
                  majorDimension:
                    type: string
                    example: "ROWS"
                  values:
                    type: array
                    items:
                      type: array
                      items:
                        type: string
    put:
      operationId: updateValues
      summary: Обновить значения в диапазоне таблицы
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
          description: ID Google таблицы
          example: "1M50MTl_pWsov4yavKR_QdfHEOZqMpr63vbK46HHPAlA"
        - name: range
          in: path
          required: true
          schema:
            type: string
          description: Диапазон ячеек (например, 'Sheet1!A1:B10')
          example: "Sheet1!A1:B10"
        - name: valueInputOption
          in: query
          schema:
            type: string
            enum: [RAW, USER_ENTERED]
            default: RAW
          description: Как интерпретировать значения
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - values
              properties:
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
              example:
                values: [["Новое значение 1", "Новое значение 2"], ["Строка 2.1", "Строка 2.2"]]
      responses:
        '200':
          description: Результат обновления
          content:
            application/json:
              schema:
                type: object
                properties:
                  spreadsheetId:
                    type: string
                  updatedRange:
                    type: string
                  updatedRows:
                    type: integer
                  updatedColumns:
                    type: integer
                  updatedCells:
                    type: integer
